## Program: VMTK
## Language:  Python
## Date:      February 19, 2026
## Version:   1.6

##   Copyright (c) Richard Izzo, Luca Antiga, All rights reserved.
##   See LICENSE file for details.

##      This software is distributed WITHOUT ANY WARRANTY; without even
##      the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
##      PURPOSE.  See the above copyright notices for more information.

package:
  name: "vmtk"
  version: "1.6.0"

source:
    path: ../

build:
  number: 0
  features:
    - vc17  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - pkgconfig              # [unix]
    - cmake >=3.16
    - git
    - ninja
  host:
    - python {{ python }}
    - vtk {{ vtk }}
    - libitk {{ itk }}
    - libitk-devel {{ itk }}
    - numpy >=1.26
    - h5py
    - tbb-devel
    - joblib

  run:
    - python {{ python }}
    - vtk {{ vtk }}
    - libitk {{ itk }}
    - numpy >=1.26
    - h5py
    - joblib

test:
  source_files:
    - build/tests/*
  requires:
    - pytest
    - pytest-html
  commands:
    - pytest  {{ environ.get('PYTEST_REPORT', '') }} -vv ./build/tests/

about:
  home: www.vmtk.org
  license_file: LICENSE
  summary: "vmtk - the Vascular Modeling Toolkit. See www.vmtk.org/ for details."
extra:
  recipe-maintainers:
    - ramtingh